### ISSUE TITLE
Unhandled Exception: PlatformException(error, Unsupported value: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null)

### ISSUE THREAD

**Issue by alectogeek** [luanpotter/audioplayers#494] opened 2020-04-14 21:00 UTC
```
E/flutter (19501): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Unsupported value: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null)
E/flutter (19501): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569)
E/flutter (19501): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321)
E/flutter (19501): <asynchronous suspension>
E/flutter (19501): #2      AudioPlayer._invokeMethod (package:audioplayers/audioplayers.dart:297)
E/flutter (19501): #3      AudioPlayer.play (package:audioplayers/audioplayers.dart:360)
E/flutter (19501): #4      AudioCache.play (package:audioplayers/audio_cache.dart:104)
E/flutter (19501): <asynchronous suspension>
```

Fluter doctor:
```
Flutter 1.12.13+hotfix.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f139b11009 (2 weeks ago) • 2020-03-30 13:57:30 -0700
Engine • revision af51afceb8
Tools • Dart 2.7.2
```

**Comment by pgainullin** [comment] 2020-12-01 04:11
potentially duplicate of #326

**Comment by erickzanardo** [comment] 2021-04-10 14:48
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening

**Closed by erickzanardo** 2021-04-10 14:48 UTC
