### ISSUE TITLE
App Crashes Abruptly

### ISSUE THREAD

**Issue by rv97** [luanpotter/audioplayers#338] opened 2019-11-27 08:29 UTC
I just created an app with a small flatbutton and in the onpressed method created an instance of audio cache and played an audio, the app closes abruptly without any error. Then i changed to version 0.10.1 it is working fine.

Error:
iOS => call startHeadlessService, playerId b295134d-9204-436e-a91d-019e2141f81b

**Comment by mavbcn** [comment] 2019-11-27 13:49
Hi have the same problem with iOS

**Comment by joshhaaronn** [comment] 2019-11-28 01:05
I am also having the same issue on iOS

**Comment by batman-dev** [comment] 2019-11-28 01:42
I am also having the same issue on iOS
When play assets mp3

Env iOS13  XCode11.2.1

**Comment by rv97** [comment] 2019-11-28 17:50
> I am also having the same issue on iOS
> ![audiobug](https://user-images.githubusercontent.com/30924169/69821582-f5941a00-11b8-11ea-9e2b-1db5191aaa8f.gif)

This is the exact issue i am also facing!

**Comment by dvorapa** [comment] 2019-11-28 19:04
@subhash279 !!!

**Comment by andrewsdv** [comment] 2019-11-30 08:53
The same for me. Could anyone help and point out the reason?

**Comment by mavbcn** [comment] 2019-11-30 09:07
Hi everyone,
I tried to use this version   audioplayers: ^0.12.1 .  and it works. 
Try to update pubspec.yaml with this version
best

**Comment by andrewsdv** [comment] 2019-11-30 09:35
> Hi everyone,
> I tried to use this version audioplayers: ^0.12.1 . and it works.
> Try to update pubspec.yaml with this version
> best

Indeed it worked for me also. Looks like the 0.13.2 is broken.

**Comment by eggnstone** [comment] 2019-11-30 12:12
See #306 
0.13.2 works for me though, only 0.13.3 doesn't work for me.

**Comment by eggnstone** [comment] 2019-11-30 12:13
Duplicate of #306

**Comment by smocken78** [comment] 2019-11-30 12:32
I had the same problem, in my case using AudioCache with fixed player and low latency mode helped:

var player = new AudioCache(
  fixedPlayer: new AudioPlayer(
    mode: PlayerMode.LOW_LATENCY,
  ),
);

**Comment by subhash279** [comment] 2019-12-02 16:03
Created a new PR #332 which should also fix this.

**Comment by JonathanIvyCR** [comment] 2019-12-04 03:16
I'm using 0.13.4 and it's still happening. It was working fine and now it's crashing every time it plays an audio.

**Comment by crizant** [comment] 2019-12-04 07:45
I'm using 0.13.4 and it crashes every time when the playback comes to end.

On iPhone 11 Pro, iOS 13.2.3.

**Comment by JesseScott** [comment] 2019-12-05 02:21
> I'm using 0.13.4 and it crashes every time when the playback comes to end.
> 
> On iPhone 11 Pro, iOS 13.2.3.

this is already tracked in https://github.com/luanpotter/audioplayers/issues/345

**Comment by luanpotter** [comment] 2019-12-05 13:43
Closing as duplicate of #345

**Closed by luanpotter** 2019-12-05 13:43 UTC
