### ISSUE TITLE
In ios media notification not generating

### ISSUE THREAD

**Issue by HetalGohil** [luanpotter/audioplayers#362] opened 2019-12-18 09:50 UTC
`
    durationSubscription = audioPlayer.onDurationChanged.listen((duration1) {

      print("duration change***$duration1");
      setState(() => duration = duration1);

      // TODO implemented for iOS, waiting for android impl
     // if (Theme.of(context).platform == TargetPlatform.iOS) {
       if(Platform.isIOS) {

        // set atleast title to see the notification bar on ios.
        audioPlayer.startHeadlessService();

        audioPlayer.setNotification(
            title: '$appname',
            artist: '${curPlayList[curPos].description}',
            albumTitle: '${curPlayList[curPos].cat_name}',
            imageUrl: '${curPlayList[curPos].image}',
            forwardSkipInterval: const Duration(seconds: 30),
            // default is 30s
            backwardSkipInterval: const Duration(seconds: 30),
            // default is 30s
            duration: duration1,
            elapsedTime: Duration(seconds: 0));
      }

    });`

i have put this code and in console run i m getting notification done but notification not gernerating

**Comment by dongxiaofen** [comment] 2019-12-27 02:54
Have you solved the problem? I have this problem, too

**Comment by Tecode** [comment] 2019-12-27 10:04
Edit code 
`BOOL success = [[AVAudioSession sharedInstance] setCategory:category withOptions:AVAudioSessionCategoryOptionMixWithOthers error:&error];`
 to 
`  BOOL success = [[AVAudioSession sharedInstance] setCategory:category error:&error];`  in IOS file [Link](https://github.com/luanpotter/audioplayers/blob/560d9871e345b94aef7b11398dfca7b524405b6d/ios/Classes/AudioplayersPlugin.m#L417)

[AVAudioSessionCategoryOptionMixWithOthers](https://developer.apple.com/documentation/avfoundation/avaudiosessioncategoryoptions/avaudiosessioncategoryoptionmixwithothers)

**Comment by vuln3r** [comment] 2019-12-31 09:31
> Edit code
> `BOOL success = [[AVAudioSession sharedInstance] setCategory:category withOptions:AVAudioSessionCategoryOptionMixWithOthers error:&error];`
> to
> ` BOOL success = [[AVAudioSession sharedInstance] setCategory:category error:&error];` in IOS file [Link](https://github.com/luanpotter/audioplayers/blob/560d9871e345b94aef7b11398dfca7b524405b6d/ios/Classes/AudioplayersPlugin.m#L417)
> 
> [AVAudioSessionCategoryOptionMixWithOthers](https://developer.apple.com/documentation/avfoundation/avaudiosessioncategoryoptions/avaudiosessioncategoryoptionmixwithothers)

I tried that and it doesn’t work :( 
also, it doesn’t work on example app

**Comment by Mamong** [comment] 2020-01-02 04:49
It maybe caused by reuse AVPlayerItem.
Try to add [self updateDuration:playerId];before [478 line](https://github.com/luanpotter/audioplayers/blob/560d9871e345b94aef7b11398dfca7b524405b6d/ios/Classes/AudioplayersPlugin.m#L417)

**Comment by Dotsung** [comment] 2020-01-13 06:22
This worked to me.
So thanks!!

**Comment by vuln3r** [comment] 2020-01-13 08:13
> It maybe caused by reuse AVPlayerItem.
>Try to add `[self` updateDuration:playerId];`before 478 line

thank you @mamong

**Comment by luanpotter** [comment] 2020-01-13 17:34
Would someone be willing to make a pr for this fix?

**Comment by pobrejuanito** [comment] 2020-01-13 21:16
> Would someone be willing to make a pr for this fix?

Hi luanpotter, there are couple pull requests open regarding this, they both address the issue.
https://github.com/luanpotter/audioplayers/pull/354
https://github.com/luanpotter/audioplayers/pull/357/

**Comment by luanpotter** [comment] 2020-11-22 02:16
Since #354 is merged, this is fixed.

**Closed by luanpotter** 2020-11-22 02:16 UTC
