### ISSUE TITLE
urred evaluating project ':audioplayers'. > Plugin with id 'kotlin-android' not found.  *

### ISSUE THREAD

**Issue by jinfagang** [luanpotter/audioplayers#718] opened 2021-01-04 12:37 UTC
```
.pub-cache\hosted\pub.flutter-io.cn\audioplayers-0.17.1\android\build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':audioplayers'.
> Plugin with id 'kotlin-android' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':audioplayers'.
> compileSdkVersion is not specified. Please add it to build.gradle
```

**Comment by MauroDiamantino** [comment] 2021-01-05 21:12
I've had the same issue. I tried a previous version of audioplayers, specifically 0.15.1, and I didn't get this error but when I tried to compile to iOS I got a lot of errors so I decided to move to the last version of audioplayers, but I cannot solve this error.

**Comment by VictorUvarov** [comment] 2021-01-06 00:39
I get the same error when i create a new project with no kotlin support `flutter create -a java my_app`. 

pubspec.yaml:
```yaml
audioplayers: ^0.17.1
```

app/build.gradle:
```gradle
defaultConfig {
  ...
  minSdkVersion 23
  ...
}
```

If i create a new project with kotlin support `flutter create my_app` (flutter create defaults to kotlin/swift)
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
lib/main.dart:1
e: /home/victor/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.17.1/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (181, 52): Expecting a parameter declaration
e: /home/victor/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.17.1/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (231, 38): Expecting an argument
e: /home/victor/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.17.1/android/src/main/kotlin/xyz/luan/audioplayers/ByteDataSource.kt: (8, 37): Expecting a parameter declaration

e: /home/victor/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.17.1/android/src/main/kotlin/xyz/luan/audioplayers/WrappedMediaPlayer.kt: (10, 39): Expecting a parameter declaration
e: /home/victor/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.17.1/android/src/main/kotlin/xyz/luan/audioplayers/WrappedSoundPool.kt: (168, 32): Expecting a parameter declaration
e: /home/victor/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.17.1/android/src/main/kotlin/xyz/luan/audioplayers/WrappedSoundPool.kt: (205, 26): Expecting an argument
e: /home/victor/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.17.1/android/src/main/kotlin/xyz/luan/audioplayers/WrappedSoundPool.kt: (46, 77): Type inference failed. Expected type mismatch: inferred type is List<???> but MutableList<WrappedSoundPool> was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':audioplayers:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Comment by koji-1009** [comment] 2021-01-07 04:54
This problem seems to be caused by `$kotlin_version` param.

`$kotlin_version` param is added at `android/build.gradle`, but `$kotlin_version` is defined only in `example/android/build.gradle`.
see https://github.com/luanpotter/audioplayers/compare/0.17.0...0.17.1

So, the build will fail for only java flutter project.
I think the `$kotlin_version` should be specified in this library.

**Comment by kivancg** [comment] 2021-01-07 05:24
Having the same issue..

**Comment by searchy2** [comment] 2021-01-07 16:06
Hope #723 can be merged and a new release ASAP.
0.17.1 is broken, cannot build.

**Comment by MATTYGILO** [comment] 2021-01-08 13:03
I am having the same issue when is it getting merged?

**Closed** 2021-01-08 13:46 UTC
Labels: bug
