### ISSUE TITLE
[ERROR] Exception has occurred. PlatformException (PlatformException(error, Unsupported value: java.lang.RuntimeException: Unable to access resource, null))

### ISSUE THREAD

**Issue by angelhdz** [luanpotter/audioplayers#486] opened 2020-04-06 02:03 UTC
Error when calling play() on an AudioPlayer instance, regardless of the parameter isLocal true or false. AudioCache().play() works good.

Exception has occurred.
PlatformException (PlatformException(error, Unsupported value: java.lang.RuntimeException: Unable to access resource, null))

![image](https://user-images.githubusercontent.com/10191085/78516811-fe10e880-7788-11ea-870a-afccfe4f2c91.png)

**Comment by smarthomecode** [comment] 2020-05-14 05:10
Focus the same issue , does it fixed now?

**Comment by angelhdz** [comment] 2020-05-14 07:12
Yes. I'm playing sounds with AudioPlayer currently as of version ^0.15.1.

But, the sounds play laggy for me, like distorted. I'm gonna try to play them locally instead to see if it's a network related issue.

**Comment by angelhdz** [comment] 2020-05-14 07:19
Ok, nevermind. I'm getting the same error when I load the files locally and set isLocal to true.

**Comment by angelhdz** [comment] 2020-05-14 08:02
So this is it's what's happening to me:

AudioPlayer error with local sound file.
AudioPlayer no error with network sound file, but the sound it's distortioned/laggy.

AudioCache no error with local sound file, but the sound it's distortioned/laggy.

**Comment by coldembrace** [comment] 2020-05-16 17:33
Getting the same issue on both Android 9 (emulator) & Android 10 (real device).

**Comment by angelhdz** [comment] 2020-05-16 18:08
> Getting the same issue on both Android 9 (emulator) & Android 10 (real device).

Thanks for confirming. I hope it gets fix soon.

**Comment by coldembrace** [comment] 2020-05-17 10:16
> Getting the same issue on both Android 9 (emulator) & Android 10 (real device).

Nvm, In my case there was an issue with the local audiofile which I was trying to play. Probably, the problem was related to an unsupported codec. 
I'd suggest everyone who suffering from this issue to double-check if your file can be played via the default android player.

**Comment by ider0614** [comment] 2020-08-28 06:09
+1

**Comment by erickzanardo** [comment] 2021-04-13 14:14
There isn't enough information on this issue for us to act on. Please edit this, or open a new one and please follow the issue template.

Feel free to comment here and we can re open this eventually.

**Closed by erickzanardo** 2021-04-13 14:14 UTC

**Comment by angelhdz** [comment] 2021-04-13 20:21
> There isn't enough information on this issue for us to act on. Please edit this, or open a new one and please follow the issue template.
> 
> Feel free to comment here and we can re open this eventually.

Without sounding rude, I've followed the Issue template many times in many technologies repositories, and people just ignore it and ask me questions that I already explained in the Issue Template, so It's a waste of time. 

That's why I prefer to explain my issues in detail and if I feel that I need to mention a technology, library, or operating system version because it's relevant to the issue, I provide it.

But in this case, it was just a general error using a pub package out of the box, following the examples.

I rarely use sounds in my apps, but I'm working on a new project where I will need sounds, so I will try a recent version of this package to see if the issue is gone, and to see if the sound lag is gone as well.

And will check if the lag it's an issue with my sounds encoding and how Android handles them. 

Thank you.

**Comment by erickzanardo** [comment] 2021-04-13 21:38
> Without being rude, I've followed the Issue template many times in many technologies repositories, and people just ignore it and ask me questions that I already explained in the Issue Template, so It's a waste of time. 
> 
> 
> 
> That's why I prefer to explain my issues in detail and if I feel that I need to mention a technology, library, or operating system version because it's relevant to the issue, I provide it.
> 
> 
> 
> But in this case, it was just a general error using a pub package out of the box, following the examples.
> 
> 
> 
> I rarely use sounds in my apps, but I'm working on a new project where I will need sounds, so I will try a recent version of this package to see if the issue is gone, and to see if the sound lag is gone as well.
> 
> 
> 
> And will check if the lag it's an issue with my sounds encoding and how Android handles them. 
> 
> 
> 
> Thank you.
> 
> 
> 
> 

The issue template, is just a template of information that we usually need to act on something, of course if the issue is well documented we will not care for the template.

The template was created after this issue was opened, we are doing some house keeping on the repository and asking people to follow the issue template as a default advice. We are doing that because there are many issue without description, info, etc, so this became a default advice for us.

Specifically on this issue what is most missing is a reproducible code and asset. 

But actually on a more carefully reading, it seems that this particular issue was fixed on newer versions of the package.

Anyhow, like I mentioned on the end of my comment, you are always welcome to comment here if you disagree with the closing of the issue and we can eventually re open it.

**Comment by angelhdz** [comment] 2021-04-13 21:39
> > Without being rude, I've followed the Issue template many times in many technologies repositories, and people just ignore it and ask me questions that I already explained in the Issue Template, so It's a waste of time.
> > That's why I prefer to explain my issues in detail and if I feel that I need to mention a technology, library, or operating system version because it's relevant to the issue, I provide it.
> > But in this case, it was just a general error using a pub package out of the box, following the examples.
> > I rarely use sounds in my apps, but I'm working on a new project where I will need sounds, so I will try a recent version of this package to see if the issue is gone, and to see if the sound lag is gone as well.
> > And will check if the lag it's an issue with my sounds encoding and how Android handles them.
> > Thank you.
> 
> The issue template, is just a template of information that we usually need to act on something, of course if the issue is well documented we will not care for the template.
> 
> The template was created after this issue was opened, we are doing some house keeping on the repository and asking people to follow the issue template as a default advice. We are doing that because there are many issue without description, info, etc, so this became a default advice for us.
> 
> Specifically on this issue what is most missing is a reproducible code and asset.
> 
> But actually on a more carefully reading, it seems that this particular issue was fixed on newer versions of the package.
> 
> Anyhow, like I mentioned on the end of my comment, you are always welcome to comment here if you disagree with the closing of the issue and we can eventually re open it.

Totally agree with everything you said. And I thank you for your kindness and time.

Cheers!
