### ISSUE TITLE
Wish- Add setSpeed() method

### ISSUE THREAD

**Issue by praharshbhatt** [luanpotter/audioplayers#323] opened 2019-11-18 04:48 UTC
This is more of a request than an issue.
I would like to have a setSpeed() method to control the speed of the currently playing audio track.
Thanks

**Comment by dvorapa** [comment] 2019-11-18 22:22
Dupe of #224: for iOS already fixed, for Android there is a patch coming: #304

**Comment by erickzanardo** [comment] 2021-04-10 14:34
Duplicate of #

**Closed by erickzanardo** 2021-04-10 14:34 UTC
