### ISSUE TITLE
Http urls not supported

### ISSUE THREAD

**Issue by noraibrahimi** [luanpotter/audioplayers#369] opened 2019-12-25 12:55 UTC
The player just doesn't start and it doesn't show any errors or warnings.

**Comment by Andrewngabriel** [comment] 2020-01-08 03:06
I ran into this issue as well and the problem is specific to Android and not with the plugin. You can find the fix [here](https://github.com/luanpotter/audioplayers/issues/383)

**Comment by luanpotter** [comment] 2020-01-11 18:53
closed in favor of #383

**Closed by luanpotter** 2020-01-11 18:53 UTC
