### ISSUE TITLE
First player stops second player when finished playing. Only happens on iOS

### ISSUE THREAD

**Issue by pierrea** [luanpotter/audioplayers#671] opened 2020-11-13 20:25 UTC
I want to play 2 sounds on top of each other, the first one being a 1 minute intro using `AudioCache` and the second being downloaded from the internet. It appears that on iOS, when the intro player is done, it pauses the second player without triggering a state change however. On Android, the second player is not affected, as expected.

**Full Description**
Here's what's going on step by step on iOS:
1. player 1 starts playing its 1 minute intro sound
2. 30 seconds later, player 2 starts playing its longer sound (I'm using a timer to delay player 2)
3. 30 seconds later, player 1's state is `COMPLETED` because the intro finished playing
4. player 1 stops playing but its state doesn't change

I'm using 2 separate `AudioPlayer` instances with 2 different `playerId`s.
The first player is the `fixedPlayer` of an `AudioCache` instance.

I tried to set release mode to `STOP` instead of `RELEASE`: `introPlayer.setReleaseMode(ReleaseMode.STOP);` but that didn't help. I also listened to `onPlayerError` streams, nothing on either player.

**Simplified code**

```dart
final AudioPlayer soundPlayer = AudioPlayer(
  playerId: "sound_player",
  mode: PlayerMode.MEDIA_PLAYER,
);
final AudioPlayer introPlayer = AudioPlayer(
  playerId: "intro_player",
  mode: PlayerMode.MEDIA_PLAYER,
);
final AudioCache audioCache = AudioCache(
  prefix: "assets/sounds/",
  respectSilence: false,
);

void launchIntro() async {
  await audioCache.play(
    "intro.m4a",
    stayAwake: true,
  );
}

void launchSound() async {
  await soundPlayer.play(
    sound.localFilePath,
    isLocal: true,
    respectSilence: false,
    stayAwake: true,
  );
}

void initPlayers() {
  audioCache.fixedPlayer = introPlayer;

  soundPlayer.onPlayerStateChanged.listen((state) {
    print("soundPlayer state: $state"); // this never shows PAUSED or STOPPED
  });
}

void play() {
  initPlayers();

  // 1
  launchIntro();

  // 2
  Timer(Duration(seconds: 30), launchSound);

  // 3
  // when introPlayer is done playing, soundPlayer stops playing as well!
}
```

Again this problem does not happen on Android.
Many thanks in advance!

**Comment by luanpotter** [comment] 2020-11-15 00:26
@pierrea this a very well document and written out issue, thanks for putting it together. It does look like a bug, as your code is has no problems that I can see. I will try to reproduce later and see what I can find.

**Comment by foodpoison** [comment] 2020-11-16 14:49
I had the same problem with `audioplayers` at `^0.16.2`, but if I drop it back down to `^0.16.1` it seems to be ok. @pierrea can you confirm?

**Comment by asiaWang** [comment] 2020-12-08 08:13
i also have this problem,it happened when play a local path audio use AudioCache .then play a url use audioplayer,can some one solve this problem?

audioplayers : ^0.16.1

**Comment by ixugo** [comment] 2021-01-06 08:40
I also have this problem ;

Not using fixedPlayer is normal ;
But the screen freezes after 5 minutes of audio playback ;

Only happens on IOS ; 

version : 0.17.0
Cannot run after Android version  upgrade by 0.17.1 # 714;

**Comment by mikeesouth** [comment] 2021-01-22 10:03
I believe that I'm also seeing this. I have a nasty bug in my application where it hangs waiting for an sound to be completed. After long debugging sessions I've narrowed it down to audioplayers. I'm playing sounds from different areas in the application but somehow two sounds are being played closed to each other and I believe that one of the players does not correctly send a state change so my application thinks that it's still playing the sound, thus waiting for the sound to be completed and waiting "forever". This only happens on iOS.

Anyone found a workaround besides setting a timer and manually marking the audio stream as completed after the expected duration for the sound?

**Comment by pierrea** [comment] 2021-01-22 10:50
Hi @mikeesouth thanks for sharing. This sounds like a similar issue indeed, although in my case the problem comes when completing a sound—it stops the whole audio even though another sound is being played independently. What I ended up doing is setting a timer that **pauses** the first sound a second before it would have been completed. It's very inconvenient but it's my workaround at the moment.

**Comment by mikeesouth** [comment] 2021-01-22 13:41
@pierrea ok, thanks for the info. After more troubleshooting it seems like this isn't the issue I'm experiencing. I'm also playing my sounds in sequence most of the time but overlaps can happen.

So, I shouldn't post more about my problem in this issue, I'll start a new issue as soon as I get more info on it. Short version is that I get an error from iOS: AVPlayerItemStatus.failed and the state changes to STOPPED (not COMPLETED). Not sure on how I can get more info on that error message though.

**Comment by mikeesouth** [comment] 2021-01-26 20:58
@pierrea I put my issue here: https://github.com/luanpotter/audioplayers/issues/746. The summary is that audioplayers lib seems to have some kind of memory leak or some other resource limitation on iOS. Creating ~750 AudioPlayers instances seems to fill some kinda quota and the audio mechanics in iOS fails. I circumvented that by re-using audioplayers in a pool.

Funny thing though - in my testing I upgraded audioplayers from 0.16.1 to 0.17.2 and when the resource leak was handled I did more tests and had problems playing overlapping/parallel sounds. I stumbled upon this very issue and to solve it, I downgraded back to 0.16.1 and it works smooth as butter again.

So, I'm using a pool of AudioPlayers to circumvent issue 746 and I'm keeping the version at 0.16.1 to circumvent this issue.

@luanpotter Do you have any clue on this issue? If not, maybe we can help with PRs but if you do have a trail already, let us know so that we don't start troubleshooting from scratch.

**Comment by erickzanardo** [comment] 2021-04-10 15:36
@pierrea can you confirm if the fixes added by #767 solved this issue?

**Comment by pierrea** [comment] 2021-04-16 17:46
@erickzanardo apologies, we switched to another player package a few weeks ago to accomplish our goals

**Comment by erickzanardo** [comment] 2021-04-28 14:34
Closing this as the linked PR probably solved this, if anyone is still facing this, please file a new issue.

**Closed by erickzanardo** 2021-04-28 14:34 UTC
Labels: bug, waiting for report
