### ISSUE TITLE
import style causes "Unhandled Exception: Bad state"

### ISSUE THREAD

**Issue by emaame** [luanpotter/audioplayers#415] opened 2020-02-06 16:16 UTC
Change import style in `'audio_cache.dart'`, please.
dart lang shows strange results if you don't use `'package:'` style import.

## Problem
Change

```dart
import 'audioplayers.dart';
```

to

```dart
import 'package:audioplayers/audioplayers.dart';
```

It causes different static/final instances for audioplayers.
In my case, A runtime error occurred with Timer callback, sorry this is not a real code, a following:

```dart
new Timer(item.durationToNext(), () {
      _audioCache.play(file);
    });
```

> E/flutter ( 6737): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Bad state: Cannot add new events after calling close
> E/flutter ( 6737): #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:251:24)
> E/flutter ( 6737): #1      AudioPlayer.state= (package:audioplayers/audioplayers.dart:168:28)
> E/flutter ( 6737): #2      AudioPlayer._doHandlePlatformCall (package:audioplayers/audioplayers.dart:559:16)
> E/flutter ( 6737): #3      AudioPlayer.platformCallHandler (package:audioplayers/audioplayers.dart:517:7)
> E/flutter ( 6737): #4      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channe

After I edit the import sentence, the error does not happen.

## See also

* [Library-private final fields get different instances depending on how the library was imported #32601](https://github.com/dart-lang/sdk/issues/32601)
* [Consider changing default convention of putting `main.dart` inside `lib/` or provide guidelines #15748](https://github.com/flutter/flutter/issues/15748)
* [Flutter/Dart Static variables lost / keep getting reinitialized](https://stackoverflow.com/questions/45772318/flutter-dart-static-variables-lost-keep-getting-reinitialized)

Thank you for your work,
regards.

**Comment by ttencate** [comment] 2020-05-18 11:27
I'm also getting this error. But far as I can tell from e.g. https://stackoverflow.com/a/50337465/14637 and various closed issues in the Dart and Flutter repositories, the confusion around different import styles has been fixed in the Dart language around 2018. @emaame How certain are you that this is actually the cause? Are you using some very old Flutter and Dart version?

**Comment by emaame** [comment] 2020-05-20 06:03
In my case this error never happen in other library even with the use of  `MethodChannel`.
It sounds so curious.

@ttencate I'm using a stable channel, it means Flutter version was 'v1.12.13+hotfix.8' or 'v1.12.13+hotfix.7' on 7th Feb.
Unfortunately I couldn't answer clearly about Dart version. I guess it was 2.1 to 2.2.
I specified below in pubspec.yaml

```
environment:
  sdk: ">=2.1.0 <3.0.0"
```

I can't check how it works in the newest version of them immediately.

**Comment by luanpotter** [comment] 2020-11-22 02:33
The issue only happens if you mix relative/absolute imports.
By using my plugin https://github.com/luanpotter/vscode-dart-import
I made sure all imports are relative in our dart code.
So there should be no conflict.

**Closed by luanpotter** 2020-11-22 02:33 UTC
