### ISSUE TITLE
i can't play my audios from localhost or local network

### ISSUE THREAD

**Issue by jkmpariab** [luanpotter/audioplayers#249] opened 2019-08-11 14:50 UTC
hey there. i just used example project and just tested the audioplayer with an audio hosted on my local machine. but when i play this on android emulator or genymotion (bridged enabled) and even my phone, nothing happens. but plays your example usrls well. now i temporarily switched to github to serve my audio files just like your example. is there any reason or i missed something?

**Comment by duncan-iaria** [comment] 2019-08-14 02:44
Are you using an iOS simulator or phone? I just ran into this issue and it turns out that by default iOS devices won't stream audio (or make api calls?) from a non https url. It's odd because my other api calls to localhost are fine ... anyway, the fix for that issue is in the bottom of this repo's README. You have to edit your .plist file.

**Comment by jkmpariab** [comment] 2019-08-14 10:51
> Are you using an iOS simulator or phone? I just ran into this issue and it turns out that by default iOS devices won't stream audio (or make api calls?) from a non https url. It's odd because my other api calls to localhost are fine ... anyway, the fix for that issue is in the bottom of this repo's README. You have to edit your .plist file.

no i'm using android phone/emulator (and also enabled non https streams over ios)

**Comment by erickzanardo** [comment] 2019-08-14 12:41
you will probably need to use adb reverse to make port forwarding to be able to access the files on your machine, since when running the app on the device/emulator, localhost is bound to that device/emulator and not the host machine.

Closing this since this is not a problem with the package. But feel free to add more comments here if needed.

**Closed by erickzanardo** 2019-08-14 12:41 UTC

**Comment by jkmpariab** [comment] 2019-08-14 13:54
> you will probably need to use adb reverse to make port forwarding to be able to access the files on your machine, since when running the app on the device/emulator, localhost is bound to that device/emulator and not the host machine.
> 
> Closing this since this is not a problem with the package. But feel free to add more comments here if needed.

please do not close. i'm using my local server api so there's no problem with connection at all and i mentioned that i just enabled bridged network on genymotion side. before submitting this comment i tested again and result was same.

**Comment by erickzanardo** [comment] 2019-08-14 14:51
Just to be sure, I tested here, and it worked, this is not a problem with the package, this is most likely a problem with your device/emulator not been able to reach your file due to network issues/configuration.

What I did to test:

- Started a http server on the `assets` folder on port `8000`
- `adb reverse tcp:8000 tcp:8000`
- Added the line `<domain includeSubdomains="true">localhost</domain>
` on `android/app/src/main/res/xml/network_security_config.xml` because of the new Android 9 security configs.

**Comment by jkmpariab** [comment] 2019-08-14 16:09
> Just to be sure, I tested here, and it worked, this is not a problem with the package, this is most likely a problem with your device/emulator not been able to reach your file due to network issues/configuration.
> 
> What I did to test:
> 
> * Started a http server on the `assets` folder on port `8000`
> * `adb reverse tcp:8000 tcp:8000`
> * Added the line `<domain includeSubdomains="true">localhost</domain> ` on `android/app/src/main/res/xml/network_security_config.xml` because of the new Android 9 security configs.

i don't know what are you doing with adb (my apologize because i'm newcomer).
but now look what i did:
    1. downloaded termux as a terminal emulator for android
    2. run this command: curl http://<my_local_server_ip_and_port>/audio/<a_ogg_audio_file> --output ogg_file.ogg
and it just works?!

**Comment by erickzanardo** [comment] 2019-08-14 16:21
I didn't tried with termux, I just replaced on of the remote urls of the example application with a localhost url, hit play on the app, and it played.

`adb reverse` is a `adb` command that makes port forwarding from your device/emulator, to the host machine, so, `adb rever tcp:8000 tcp:8000` is basically telling your device/emulator to when the port 8000 is accessed on on the device/emulator, it should be redirected to the port 8000 from your machine.

That is the way people use to access local files of the host machine on device/emulators.

**Comment by jkmpariab** [comment] 2019-08-14 16:25
> I didn't tried with termux, I just replaced on of the remote urls of the example application with a localhost url, hit play on the app, and it played.
> 
> `adb reverse` is a `adb` command that makes port forwarding from your device/emulator, to the host machine, so, `adb rever tcp:8000 tcp:8000` is basically telling your device/emulator to when the port 8000 is accessed on on the device/emulator, it should be redirected to the port 8000 from your machine.
> 
> That is the way people use to access local files of the host machine on device/emulators.

so what about my web server logs? i mean the connection is ok. the problem is not my connection

**Comment by erickzanardo** [comment] 2019-08-14 17:17
Hmm, I did not payed attention to the part you said the server logged the incoming requests.

I noticed you accessed the url through http, and not https. Is this Android >= 8? that versions of Android does not allow access to file through http by default, you need to configure it to enable by adding that line I commented before, or use the android:usesCleartextTraffic option, [check this link](https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted) for more information about this, the info there is very good explained.

**Comment by jkmpariab** [comment] 2019-08-14 17:31
> Hmm, I did not payed attention to the part you said the server logged the incoming requests.
> 
> I noticed you accessed the url through http, and not https. Is this Android >= 8? that versions of Android does not allow access to file through http by default, you need to configure it to enable by adding that line I commented before, or use the android:usesCleartextTraffic option, [check this link](https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted) for more information about this, the info there is very good explained.

yea, my emulators using android 9.0 but my phone is an android 4.4 device?

**Comment by erickzanardo** [comment] 2019-08-14 17:39
On the emulator the problema should be the `https` problem then, try setting one of the options presented on the link from my last comment. If that doesn't work I would recommend you downloading the file on the device to test, maybe there is some issue with the web server, or even with the file.

If you want to, and if possible of course, send us the file so we can test here, to make sure that the problem is not with the file.

**Comment by jkmpariab** [comment] 2019-08-14 17:43
> On the emulator the problema should be the `https` problem then, try setting one of the options presented on the link from my last comment. If that doesn't work I would recommend you downloading the file on the device to test, maybe there is some issue with the web server, or even with the file.
> 
> If you want to, and if possible of course, send us the file so we can test here, to make sure that the problem is not with the file.

 i will check this out for emulators as soon as i can

**Comment by jkmpariab** [comment] 2019-08-14 18:04
> On the emulator the problema should be the `https` problem then, try setting one of the options presented on the link from my last comment. If that doesn't work I would recommend you downloading the file on the device to test, maybe there is some issue with the web server, or even with the file.
> 
> If you want to, and if possible of course, send us the file so we can test here, to make sure that the problem is not with the file.

thank you man. it was my fault. android 9+ do not support cleartext files by default

**Comment by jkmpariab** [comment] 2019-08-14 18:18
i think you should mention this android restrictions, on documentation or readme file just as ios

**Comment by erickzanardo** [comment] 2019-08-14 18:29
It already is, on README we ask people to look the troubleshoot.md before openning issues,
there we mention about that 😉 

Anyway, I am glad you got it working :)

**Comment by jkmpariab** [comment] 2019-08-16 20:26
> It already is, on README we ask people to look the troubleshoot.md before openning issues,
> there we mention about that 
> 
> Anyway, I am glad you got it working :)

excuse me for inattention. i wish it was on main page just like ios
