### ISSUE TITLE
can't find interrupt callback

### ISSUE THREAD

**Issue by JimmyKent** [luanpotter/audioplayers#606] opened 2020-08-17 09:55 UTC
in iOS, I play audio in background, open another player and play song, I can't find any callback, but it's pause.
I have ever try 
onPlayerStateChanged 
onDurationChanged 
onPlayerCompletion
onPlayerError
onNotificationPlayerStateChanged
onAudioPositionChanged

all of them didn't callback.

**Comment by geedevelopers** [comment] 2020-08-20 20:38
Same here

**Comment by luanpotter** [comment] 2020-09-21 03:24
sorry, I don't quite understand what you are talking about. please provide:

* some code reproducing the problem
* what you expect to see vs what happens
* what platforms you tested it in, in detail

**Comment by luanpotter** [comment] 2020-10-13 12:25
Please follow the issue template carefully, otherwise I will just close the issue.

**Comment by JimmyKent** [comment] 2020-10-14 12:27
in Android, we have a callback as onAudioFocusChange, when audio player is interrupt by other application. then we can change play button in player's view.
in this player, I can't find some callbacks like this.

**Comment by erickzanardo** [comment] 2021-04-13 15:10
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening

**Closed by erickzanardo** 2021-04-13 15:10 UTC

**Comment by fullflash** [comment] 2024-01-22 03:09
onPlayerStateChanged is not triggered when user receives incoming call. and there is no other callbacks as issue owner mentioned. why issue is closed ?
