### ISSUE TITLE
Exception when using monitorNotificationStateChanges()

### ISSUE THREAD

**Issue by volgin** [luanpotter/audioplayers#405] opened 2020-01-27 18:33 UTC
I could not understand what this method does, so I decided to try it.  When calling this method I get the following exception (before a player does anything):

```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'toRawHandle' was called on null.
Receiver: null
Tried calling: toRawHandle()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      AudioPlayer.monitorNotificationStateChanges (package:audioplayers/audioplayers.dart:332:44)

```

Does anyone know what this method does, and why it crashes?

**Comment by MATTYGILO** [comment] 2020-11-10 19:53
I am having the same issue. How do you fix it

**Comment by luanpotter** [comment] 2021-04-05 17:07
I believe this has been fixed, there is an assert now:

```
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      // Start the headless audio service. The parameter here is a handle to
      // a callback managed by the Flutter engine, which allows for us to pass
      // references to our callbacks between isolates.
      final CallbackHandle? handle =
          PluginUtilities.getCallbackHandle(_backgroundCallbackDispatcher);
      assert(handle != null, 'Unable to lookup callback.');
      _invokeMethod('startHeadlessService', {
        'handleKey': <dynamic>[handle?.toRawHandle()],
      });
    }
```

The issue is that that is only implemented for iOS. I believe you tried using it on android right @volgin @MATTYGILO ?

We should probably improve the error message to link to some better references and possibly add the ios only if on more places where the handle is used.

**Comment by erickzanardo** [comment] 2021-04-13 13:52
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening

**Closed by erickzanardo** 2021-04-13 13:52 UTC
