### ISSUE TITLE
Kotlin error 0.17.2

### ISSUE THREAD

**Issue by jinfagang** [luanpotter/audioplayers#738] opened 2021-01-19 11:20 UTC
```
e: D:\flutter\.pub-cache\hosted\pub.flutter-io.cn\audioplayers-0.17.2\android\src\main\kotlin\xyz\luan\audioplayers\AudioplayersPlugin.kt: (181, 52): Expecting a parameter declaration
e: D:\flutter\.pub-cache\hosted\pub.flutter-io.cn\audioplayers-0.17.2\android\src\main\kotlin\xyz\luan\audioplayers\AudioplayersPlugin.kt: (231, 38): Expecting an argument
e: D:\flutter\.pub-cache\hosted\pub.flutter-io.cn\audioplayers-0.17.2\android\src\main\kotlin\xyz\luan\audioplayers\ByteDataSource.kt: (8, 37): Expecting a parameter declaration
e: D:\flutter\.pub-cache\hosted\pub.flutter-io.cn\audioplayers-0.17.2\android\src\main\kotlin\xyz\luan\audioplayers\WrappedMediaPlayer.kt: (10, 39): Expecting a parameter declaration
e: D:\flutter\.pub-cache\hosted\pub.flutter-io.cn\audioplayers-0.17.2\android\src\main\kotlin\xyz\luan\audioplayers\WrappedSoundPool.kt: (168, 32): Expecting a parameter declaration
e: D:\flutter\.pub-cache\hosted\pub.flutter-io.cn\audioplayers-0.17.2\android\src\main\kotlin\xyz\luan\audioplayers\WrappedSoundPool.kt: (205, 26): Expecting an argument
e: D:\flutter\.pub-cache\hosted\pub.flutter-io.cn\audioplayers-0.17.2\android\src\main\kotlin\xyz\luan\audioplayers\WrappedSoundPool.kt: (46, 77): Type inference failed. Expected type mismatch: inferred type is List<???> but MutableList<WrappedSoundPool> was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':audioplayers:compileDebugKotlin'.
> Compilation error. See log for more details
```

**Comment by muarachmann** [comment] 2021-01-19 11:58
Duplicate of #737

**Comment by esiqveland** [comment] 2021-01-19 20:04
See https://github.com/luanpotter/audioplayers/issues/714#issuecomment-753747631

**Comment by luanpotter** [comment] 2021-02-23 18:10
Closing in lieu of #737

**Closed by luanpotter** 2021-02-23 18:10 UTC
Labels: bug
